services:
  join_server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["CMD", "./join_server"]

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - PGHOST=localhost
      - PGPORT=5432
      - PGDATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
